import {
  Injectable,
  NotFoundException,
  BadRequestException,
  ForbiddenException,
} from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { promises as fs } from 'fs';
import * as path from 'path';
import { randomUUID } from 'crypto';
import { VisitorEntry, VisitorEntryStatus, Location, LocationStatus } from '../entities';
import { Division } from '../../organization/entities/division.entity';
import { HrEmployee } from '../../hr/entities/hr-employee.entity';
import { CreateVisitorEntryDto } from '../dto';
import { applyDivisionScopeFilter } from '../../../common/division-scope.util';
import { UUID_SHAPE, normalizeCnic, maskCnic } from '../../../common/validators';
import { ActivityLogService } from '../../audit/services/activity-log.service';

/** The photo is personal data — keep it small and image-only (mirrors receipts). */
export const MAX_PHOTO_BYTES = 5 * 1024 * 1024;
const PHOTO_MIME_EXT: Record<string, string> = {
  'image/jpeg': '.jpg',
  'image/jpg': '.jpg',
  'image/png': '.png',
  'image/webp': '.webp',
};

export interface HostOption {
  id: string;
  employeeCode: string;
  name: string;
  department: string | null;
  divisionId: string | null;
}

export interface PhotoRef {
  absolutePath: string;
  mime: string;
}

/**
 * Visitor Entry service (Prompt #17).
 *
 * Authorization model (§11/§12) is enforced HERE as well as in `DivisionScopeGuard`
 * — never trust the frontend:
 *   • every read/write is scoped to the caller's company
 *   • `allowedDivisionIds` (user org scope ∩ role-permission division scope)
 *     filters every list and is re-checked for every single-row operation
 *   • a location must belong to the submitted division
 *   • a host must exist, be active, be in the caller's company and inside the
 *     caller's divisions
 *   • `time_in` is generated by the server; `time_out` stays NULL (Prompt #18)
 */
@Injectable()
export class VisitorEntryService {
  private readonly storagePath = path.resolve(process.env.STORAGE_PATH || './storage');

  constructor(
    @InjectRepository(VisitorEntry)
    private readonly visitorRepo: Repository<VisitorEntry>,
    @InjectRepository(Location)
    private readonly locationRepo: Repository<Location>,
    @InjectRepository(Division)
    private readonly divisionRepo: Repository<Division>,
    @InjectRepository(HrEmployee)
    private readonly employeeRepo: Repository<HrEmployee>,
    private readonly activityLog: ActivityLogService,
  ) {}

  // ─────────────────────────────────────────────────────────── CREATE ─────
  async create(
    dto: CreateVisitorEntryDto,
    companyId: string,
    userId?: string,
    allowedDivisionIds?: string[],
  ): Promise<VisitorEntry> {
    // 1. Division must belong to the caller's company AND to their divisions.
    if (Array.isArray(allowedDivisionIds) && !allowedDivisionIds.includes(dto.divisionId)) {
      throw new ForbiddenException('You do not have access to this division.');
    }
    const division = await this.divisionRepo.findOne({ where: { id: dto.divisionId, companyId } });
    if (!division) {
      throw new BadRequestException('Selected division does not exist');
    }

    // 2. Location must exist in the same company AND inside that same division.
    const location = await this.locationRepo.findOne({ where: { id: dto.locationId, companyId } });
    if (!location) {
      throw new BadRequestException('Selected location does not exist');
    }
    if (location.divisionId !== dto.divisionId) {
      throw new BadRequestException('Selected location does not belong to the selected division');
    }
    if (location.status !== LocationStatus.ACTIVE) {
      throw new BadRequestException('Selected location is not active');
    }

    // 3. Host — existing employee master, validated server-side (§10).
    const host = await this.employeeRepo.findOne({
      where: { id: dto.hostEmployeeId, companyId },
      relations: { department: true },
    });
    if (!host) {
      throw new BadRequestException('Selected person being visited does not exist');
    }
    if (host.status !== 'ACTIVE') {
      throw new BadRequestException('Selected person being visited is not an active employee');
    }
    const hostDivisionId = host.department?.divisionId ?? null;
    if (hostDivisionId && Array.isArray(allowedDivisionIds) && !allowedDivisionIds.includes(hostDivisionId)) {
      throw new ForbiddenException('The selected person belongs to a division you do not have access to.');
    }

    // 4. SERVER-SIDE Time-In + PENDING. Nothing here reads `dto.timeIn`.
    const now = new Date();
    const entry = this.visitorRepo.create({
      companyId,
      divisionId: division.id,
      locationId: location.id,
      visitorName: dto.visitorName.trim(),
      cnic: normalizeCnic(dto.cnic) ?? dto.cnic,
      mobile: dto.mobile,
      visitorCompany: dto.visitorCompany?.trim() || null,
      hostEmployeeId: host.id,
      hostNameSnapshot: [host.firstName, host.lastName].filter(Boolean).join(' ').trim() || host.employeeCode,
      photoPath: null,
      photoMime: null,
      timeIn: now,
      timeOut: null,
      status: VisitorEntryStatus.PENDING,
      createdBy: userId,
      updatedBy: userId,
    });

    const saved = await this.visitorRepo.save(entry);

    // Audit (§18) — never logs CNIC or any other visitor personal data (§19).
    await this.activityLog.log({
      actorUserId: userId,
      action: 'CREATE',
      targetType: 'visitor_entry',
      targetId: saved.id,
      targetName: saved.visitorName,
      details: `Visitor registered for ${division.name} / ${location.name}`,
    });

    return saved;
  }

  // ──────────────────────────────────────────────────────────── LIST ──────
  async findAll(options: {
    companyId: string;
    page?: number;
    limit?: number;
    search?: string;
    status?: VisitorEntryStatus;
    divisionId?: string;
    locationId?: string;
    allowedDivisionIds?: string[];
  }): Promise<{ data: any[]; total: number }> {
    const page = Math.max(1, options.page ?? 1);
    const limit = Math.min(200, Math.max(1, options.limit ?? 25));

    const qb = this.visitorRepo
      .createQueryBuilder('ve')
      .leftJoinAndSelect('ve.division', 'div')
      .leftJoinAndSelect('ve.location', 'loc')
      .where('ve.company_id = :companyId', { companyId: options.companyId });

    // §11 — never return visitors outside the caller's divisions.
    applyDivisionScopeFilter(qb, 've.divisionId', options.allowedDivisionIds);

    if (options.divisionId) {
      qb.andWhere('ve.divisionId = :divisionId', { divisionId: options.divisionId });
    }
    if (options.locationId) {
      qb.andWhere('ve.locationId = :locationId', { locationId: options.locationId });
    }
    if (options.status) {
      qb.andWhere('ve.status = :status', { status: options.status });
    }
    if (options.search && options.search.trim()) {
      qb.andWhere(
        '(ve.visitor_name ILIKE :q OR ve.visitor_company ILIKE :q OR ve.host_name_snapshot ILIKE :q OR ve.mobile ILIKE :q OR ve.cnic ILIKE :q)',
        { q: `%${options.search.trim()}%` },
      );
    }

    qb.orderBy('ve.timeIn', 'DESC').skip((page - 1) * limit).take(limit);

    const [rows, total] = await qb.getManyAndCount();
    return { data: rows.map((row) => this.toListView(row)), total };
  }

  // ────────────────────────────────────────────────────────── DETAIL ──────
  async findOne(id: string, companyId: string, allowedDivisionIds?: string[]): Promise<any> {
    const entry = await this.findRow(id, companyId, allowedDivisionIds);
    return this.toDetailView(entry);
  }

  // ─────────────────────────────────────────────────────── HOST LOOKUP ────
  async findHosts(
    companyId: string,
    allowedDivisionIds?: string[],
    options?: { search?: string; divisionId?: string; limit?: number },
  ): Promise<HostOption[]> {
    const qb = this.employeeRepo
      .createQueryBuilder('e')
      .leftJoinAndSelect('e.department', 'dept')
      .where('e.company_id = :companyId', { companyId })
      .andWhere('e.status = :status', { status: 'ACTIVE' });

    if (options?.divisionId) {
      qb.andWhere('dept.division_id = :hostDivisionId', { hostDivisionId: options.divisionId });
    } else {
      applyDivisionScopeFilter(qb, 'dept.divisionId', allowedDivisionIds);
    }

    const search = options?.search?.trim();
    if (search) {
      qb.andWhere('(e.first_name ILIKE :q OR e.last_name ILIKE :q OR e.employee_code ILIKE :q)', {
        q: `%${search}%`,
      });
    }

    // TypeORM resolves ORDER BY through entity property paths, not raw column
    // names — `e.first_name` throws "databaseName of undefined" at execution.
    qb.orderBy('e.firstName', 'ASC').addOrderBy('e.lastName', 'ASC').take(Math.min(100, options?.limit ?? 50));
    const rows = await qb.getMany();

    return rows.map((employee) => ({
      id: employee.id,
      employeeCode: employee.employeeCode,
      name: [employee.firstName, employee.lastName].filter(Boolean).join(' ').trim() || employee.employeeCode,
      department: employee.department?.name ?? null,
      divisionId: employee.department?.divisionId ?? null,
    }));
  }

  // ─────────────────────────────────────────────────────────── PHOTO ──────
  async savePhoto(
    entryId: string,
    companyId: string,
    userId: string | undefined,
    file: { originalname?: string; mimetype?: string; buffer: Buffer } | undefined,
    allowedDivisionIds?: string[],
  ): Promise<any> {
    const entry = await this.findRow(entryId, companyId, allowedDivisionIds);

    if (!file || !file.buffer) {
      throw new BadRequestException('Visitor photo file is required');
    }
    const extension = PHOTO_MIME_EXT[file.mimetype ?? ''];
    if (!extension) {
      throw new BadRequestException('Visitor photo must be a JPEG, PNG or WebP image');
    }
    if (file.buffer.length > MAX_PHOTO_BYTES) {
      throw new BadRequestException('Visitor photo must be 5 MB or smaller');
    }

    const relativePath = path.posix.join('visitors', companyId, entry.id, `${randomUUID()}${extension}`);
    const absolutePath = path.resolve(this.storagePath, relativePath);
    await fs.mkdir(path.dirname(absolutePath), { recursive: true });
    await fs.writeFile(absolutePath, file.buffer);

    if (entry.photoPath) {
      await fs.unlink(path.resolve(this.storagePath, entry.photoPath)).catch(() => undefined);
    }
    entry.photoPath = relativePath;
    entry.photoMime = file.mimetype ?? null;
    entry.updatedBy = userId ?? null;

    const saved = await this.visitorRepo.save(entry);

    await this.activityLog.log({
      actorUserId: userId,
      action: 'UPDATE',
      targetType: 'visitor_entry',
      targetId: saved.id,
      targetName: saved.visitorName,
      details: 'Visitor photo attached',
    });

    return this.toDetailView(saved);
  }

  /** Resolve the stored photo only after permission + division checks passed. */
  async resolvePhoto(
    entryId: string,
    companyId: string,
    allowedDivisionIds?: string[],
  ): Promise<PhotoRef | null> {
    const entry = await this.findRow(entryId, companyId, allowedDivisionIds);
    if (!entry.photoPath) return null;

    const absolutePath = path.resolve(this.storagePath, entry.photoPath);
    // Defence in depth: never serve a path that escaped STORAGE_PATH.
    if (!absolutePath.startsWith(this.storagePath + path.sep)) {
      throw new NotFoundException('Visitor photo not found');
    }
    const stat = await fs.stat(absolutePath).catch(() => null);
    if (!stat || !stat.isFile()) return null;

    return { absolutePath, mime: entry.photoMime || 'image/jpeg' };
  }

  // ──────────────────────────────────────────────────────── HELPERS ───────
  private async findRow(id: string, companyId: string, allowedDivisionIds?: string[]): Promise<VisitorEntry> {
    if (!UUID_SHAPE.test(String(id))) {
      throw new NotFoundException('Visitor entry not found');
    }

    const entry = await this.visitorRepo.findOne({
      where: { id, companyId },
      relations: { division: true, location: true },
    });
    if (!entry) {
      throw new NotFoundException('Visitor entry not found');
    }

    // §14 — a guessed id outside the caller's divisions must not be readable.
    if (Array.isArray(allowedDivisionIds) && !allowedDivisionIds.includes(entry.divisionId)) {
      throw new ForbiddenException('You do not have access to this visitor record.');
    }

    return entry;
  }

  /** List row: CNIC masked, internal photo path never exposed (§13/§19). */
  private toListView(entry: VisitorEntry): any {
    return {
      id: entry.id,
      companyId: entry.companyId,
      divisionId: entry.divisionId,
      locationId: entry.locationId,
      visitorName: entry.visitorName,
      cnic: maskCnic(entry.cnic),
      mobile: entry.mobile,
      visitorCompany: entry.visitorCompany,
      hostEmployeeId: entry.hostEmployeeId,
      hostNameSnapshot: entry.hostNameSnapshot,
      timeIn: entry.timeIn,
      timeOut: entry.timeOut,
      status: entry.status,
      hasPhoto: !!entry.photoPath,
      createdAt: entry.createdAt,
      createdBy: entry.createdBy,
      division: entry.division ? { id: entry.division.id, divisionCode: entry.division.divisionCode, name: entry.division.name } : null,
      location: entry.location ? { id: entry.location.id, locationCode: entry.location.locationCode, name: entry.location.name } : null,
    };
  }

  /** Detail row: full CNIC (§14) plus the authenticated photo endpoint. */
  private toDetailView(entry: VisitorEntry): any {
    return {
      ...this.toListView(entry),
      cnic: entry.cnic,
      photoUrl: entry.photoPath ? `/visitor/entries/${entry.id}/photo` : null,
      updatedBy: entry.updatedBy,
      updatedAt: entry.updatedAt,
    };
  }
}
