import { IsString, IsNotEmpty, IsOptional, MaxLength, Matches, IsIn, IsInt, Min, Max, IsBoolean } from 'class-validator';
import { Transform } from 'class-transformer';
import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsUuid, CNIC_PATTERN, MOBILE_PATTERN, normalizeMobile } from '../../../common/validators';
import { VisitorEntryStatus } from '../entities';

/**
 * CREATE VISITOR ENTRY (Prompt #17 §5 / §8 / §16).
 *
 * Deliberately ABSENT from this DTO — the global ValidationPipe runs with
 * `whitelist: true, forbidNonWhitelisted: true`, so a client that sends any of
 * them gets a 400 instead of the value being silently trusted:
 *
 *   timeIn            server-generated on create (§8)
 *   timeOut           server-generated on exit, PATCH /visitor/entries/:id/exit (§4)
 *   status            always PENDING on create (§9)
 *   exitedBy          recorded server-side together with the Time-Out (§17)
 *   companyId         derived from the caller's org scope
 *   hostNameSnapshot  derived server-side from the employee master
 *   photoPath/photoMime uploaded through POST /visitor/entries/:id/photo
 */
export class CreateVisitorEntryDto {
  @ApiProperty({ description: 'Division the visitor is entering (UUID)' })
  @IsUuid()
  @IsNotEmpty()
  divisionId: string;

  @ApiProperty({ description: 'Location inside that division (UUID)' })
  @IsUuid()
  @IsNotEmpty()
  locationId: string;

  @ApiProperty({ description: 'Visitor full name' })
  @IsString()
  @IsNotEmpty()
  @MaxLength(255)
  visitorName: string;

  @ApiProperty({
    description: 'CNIC — 13 digits or formatted 00000-0000000-0',
    example: '12345-1234567-1',
  })
  @IsString()
  @IsNotEmpty()
  @Matches(CNIC_PATTERN, {
    message: 'CNIC must be 13 digits or formatted as 00000-0000000-0',
  })
  cnic: string;

  @ApiProperty({ description: 'Mobile number', example: '0300-1234567' })
  @Transform(({ value }) => (typeof value === 'string' ? normalizeMobile(value) : value))
  @IsString()
  @IsNotEmpty()
  @MaxLength(20)
  @Matches(MOBILE_PATTERN, {
    message: 'Mobile number must be a valid number, e.g. 0300-1234567',
  })
  mobile: string;

  @ApiPropertyOptional({ description: 'Visitor company / source' })
  @IsString()
  @IsOptional()
  @MaxLength(255)
  visitorCompany?: string;

  @ApiProperty({ description: 'Person being visited — existing employee id (UUID)' })
  @IsUuid()
  @IsNotEmpty()
  hostEmployeeId: string;
}

/**
 * Exit / Time-Out payload (Prompt #18 §4).
 *
 * The exit request carries NO fields of its own: the Time-Out is generated by
 * the server (`VisitorEntryService.checkOut`).
 *
 * WHY A PLAIN RECORD AND NOT AN EMPTY DTO CLASS
 *   Nest's ValidationPipe only validates DTO *classes*, and a class with no
 *   validation metadata makes class-validator raise
 *   "an unknown value was passed to the validate function" for EVERY payload —
 *   an empty body included (verified against the versions this project runs).
 *   An `export class ExitVisitorEntryDto {}` would therefore 400 every single
 *   checkout. Typing the body as a record makes the pipe skip it
 *   (`toValidate` excludes `Object`), so the enforcement is the explicit,
 *   self-documenting server-owned key check in
 *   `VisitorEntryController.assertNoClientExitFields`, which runs before the
 *   service and answers 400 with the offending field names.
 */
export type ExitVisitorEntryBody = Record<string, unknown>;

/**
 * Host-signature size budget (Prompt #19 §14/§22).
 *
 * WHY THE CAP IS SMALL
 *   A signature is a thin line drawing, never a photograph: a signature-pad PNG
 *   is normally 5–20 KB. `MAX_SIGNATURE_BYTES` is the decoded byte cap and
 *   `MAX_SIGNATURE_DATA_URL_CHARS` the cap on the data URL the client may send.
 *
 *   The cap is deliberately below the platform's default JSON body limit
 *   (Express `json()` = 100 KB), so an oversized signature is refused with a
 *   clean, explained 400 from validation instead of an opaque 413 from the body
 *   parser — and the global parser limit never has to be widened for the whole
 *   ERP just to accept a signature.
 */
export const MAX_SIGNATURE_BYTES = 60 * 1024;
export const MAX_SIGNATURE_DATA_URL_CHARS = 85_000;

/**
 * Host confirmation payload (Prompt #19 §12/§14).
 *
 * Deliberately ABSENT — the same server-owned rule as the exit endpoint:
 *   hostConfirmed / hostConfirmedAt / hostConfirmedBy  always written server-side
 *   timeOut / status / timeIn / exitedBy               never touched here (§28)
 *   signaturePath / signatureMime / signatureCapturedAt/By  derived server-side
 *   companyId / divisionId / locationId / hostEmployeeId    never changed
 *
 * `signature` is OPTIONAL because the host may sign the physical slip instead
 * (§13/§14). When present it must be a PNG data URL produced by the frontend
 * signature pad; the service decodes it, checks the size and stores it as a
 * PRIVATE file under STORAGE_PATH — the base64 string itself is never persisted
 * in the visitor row (§22).
 */
export class ConfirmHostVisitDto {
  @ApiPropertyOptional({
    description:
      'Optional digital signature of the host as a PNG data URL. Stored as a private file, never as base64 in the visitor row.',
    example: 'data:image/png;base64,iVBORw0KGgo...',
  })
  @IsString()
  @IsOptional()
  @MaxLength(MAX_SIGNATURE_DATA_URL_CHARS)
  @Matches(/^data:image\/png;base64,[A-Za-z0-9+/]+={0,2}$/, {
    message: 'Signature must be a PNG data URL (data:image/png;base64,...)',
  })
  signature?: string;

  @ApiPropertyOptional({
    description: 'Optional free-text note recorded in the audit log (never printed on the slip).',
  })
  @IsString()
  @IsOptional()
  @MaxLength(200)
  note?: string;
}

/** Whitelisted query string for GET /visitor/entries (§13 list + filter/pagination). */
export class ListVisitorEntriesQueryDto {
  @ApiPropertyOptional({ description: 'Page number', default: 1 })
  @IsInt()
  @Min(1)
  @IsOptional()
  page?: number;

  @ApiPropertyOptional({ description: 'Page size', default: 25 })
  @IsInt()
  @Min(1)
  @Max(200)
  @IsOptional()
  limit?: number;

  @ApiPropertyOptional({ description: 'Free-text search' })
  @IsString()
  @IsOptional()
  @MaxLength(100)
  search?: string;

  @ApiPropertyOptional({
    description:
      'Status filter. PENDING returns only visitors still on site (status = PENDING AND time_out IS NULL); ' +
      'COMPLETED returns only closed visits (time_out IS NOT NULL).',
    enum: VisitorEntryStatus,
  })
  @IsIn(Object.values(VisitorEntryStatus))
  @IsOptional()
  status?: VisitorEntryStatus;

  @ApiPropertyOptional({
    description: 'Restrict to the current server-side day (today=True). Boundaries are computed on the server.',
  })
  @Transform(({ value }) => value === true || value === 'true' || value === '1')
  @IsBoolean()
  @IsOptional()
  today?: boolean;

  @ApiPropertyOptional({ description: 'Division filter (must be an authorised division)' })
  @IsUuid()
  @IsOptional()
  divisionId?: string;

  @ApiPropertyOptional({ description: 'Location filter' })
  @IsUuid()
  @IsOptional()
  locationId?: string;
}

/** Whitelisted query string for GET /visitor/hosts (§10 host lookup). */
export class HostLookupQueryDto {  @ApiPropertyOptional({ description: 'Search by name or employee code' })
  @IsString()
  @IsOptional()
  @MaxLength(100)
  search?: string;

  @ApiPropertyOptional({ description: 'Restrict to one division (must be authorised)' })
  @IsUuid()
  @IsOptional()
  divisionId?: string;

  @ApiPropertyOptional({ description: 'Max rows', default: 50 })
  @IsInt()
  @Min(1)
  @Max(100)
  @IsOptional()
  limit?: number;
}
