import {
  Controller,
  Get,
  Post,
  Patch,
  Body,
  Param,
  Query,
  Req,
  Res,
  HttpCode,
  HttpStatus,
  UseGuards,
  UseInterceptors,
  UploadedFile,
  BadRequestException,
  NotFoundException,
} from '@nestjs/common';
import { FileInterceptor } from '@nestjs/platform-express';
import { createReadStream } from 'fs';
import type { Response } from 'express';
import { PermissionGuard, RequirePermission } from '../../auth/guards/permission.guard';
import { SupabaseJwtGuard } from '../../auth/guards/supabase-jwt.guard';
import { OrgScopeGuard, RequireOrgScope } from '../../auth/guards/org-scope.guard';
import { DivisionScopeGuard, divisionFilterFromRequest } from '../../auth/guards/division-scope.guard';
import { ApiTags, ApiOperation, ApiResponse, ApiParam, ApiBearerAuth } from '@nestjs/swagger';
import { VisitorEntryService, MAX_PHOTO_BYTES } from '../services';
import {
  ConfirmHostVisitDto,
  CreateVisitorEntryDto,
  ListVisitorEntriesQueryDto,
  HostLookupQueryDto,
} from '../dto';
import type { ExitVisitorEntryBody } from '../dto';

/**
 * Server-owned keys a checkout payload must never contain (Prompt #18 §4).
 *
 * This check — not the ValidationPipe — is what enforces "the Time-Out is the
 * server's": the exit body is typed as a plain record (see `ExitVisitorEntryBody`
 * for why an empty DTO class would 400 every checkout), so nothing else stands
 * between a client and the service. It runs before the service is called, so a
 * forged Time-Out never reaches the state transition.
 */
const CLIENT_OWNED_EXIT_KEYS = [
  'timeOut',
  'time_out',
  'exitTime',
  'exit_time',
  'completedAt',
  'completed_at',
  'status',
  'exitedBy',
  'exited_by',
  'companyId',
  'divisionId',
  'locationId',
  'timeIn',
  'time_in',
  'updatedBy',
] as const;

/**
 * Server-owned keys a host-confirmation payload must never contain
 * (Prompt #19 §17/§28).
 *
 * The exit list above already covers the visit-lifecycle keys, so the two sets
 * stay deliberately separate: a rejection message tells the user which rule they
 * hit ("Time-Out is generated by the server" vs "Host confirmation is recorded
 * by the server") instead of one vague error. `ConfirmHostVisitDto` also
 * declares neither of them, so with `forbidNonWhitelisted: true` the global
 * ValidationPipe already answers 400 — this explicit list keeps the guarantee
 * independent of the pipe's configuration, exactly as the exit endpoint does.
 */
const CLIENT_OWNED_HOST_KEYS = [
  ...CLIENT_OWNED_EXIT_KEYS,
  'hostConfirmed',
  'host_confirmed',
  'hostConfirmedAt',
  'host_confirmed_at',
  'hostConfirmedBy',
  'host_confirmed_by',
  'hostEmployeeId',
  'host_employee_id',
  'hostNameSnapshot',
  'signaturePath',
  'signature_path',
  'signatureMime',
  'signature_mime',
  'signatureCapturedAt',
  'signature_captured_at',
  'signatureCapturedBy',
  'signature_captured_by',
  'visitorReference',
  'visitor_reference',
] as const;

/**
 * Visitor Entry API (Prompt #17) + exit (Prompt #18) + slip/host confirmation
 * (Prompt #19).
 *
 * Standard guard chain: JWT → PermissionGuard → OrgScopeGuard → DivisionScopeGuard.
 * `DivisionScopeGuard` rejects an explicit `divisionId` outside the caller's
 * effective division set before the handler runs; the service then re-checks
 * every row, so a guessed entry id still cannot be read (§11/§14).
 *
 * Time-In is never accepted from the client — `CreateVisitorEntryDto` does not
 * declare `timeIn`, and the global ValidationPipe runs with
 * `forbidNonWhitelisted: true`, so sending it is a 400. Time-Out is the same
 * idea with a different mechanism: the exit body is a plain record and
 * `assertNoClientExitFields` rejects every server-owned key (§4). The host
 * confirmation applies the identical rule to its own server-owned columns
 * (#19 §17/§28).
 *
 * Printing is gated by its own permission (`visitor.slip.print`, migration
 * ERP-00071) so a role can be allowed to read visitors without also being
 * allowed to produce the physical document, while host confirmation reuses
 * `visitor.entry.update` because it is literally an update of the entry.
 */
@ApiTags('visitor')
@Controller('visitor')
@ApiBearerAuth()
@UseGuards(SupabaseJwtGuard, PermissionGuard, OrgScopeGuard, DivisionScopeGuard)
export class VisitorEntryController {
  constructor(private readonly visitorService: VisitorEntryService) {}

  private getCompanyId(req: any): string {
    const companyId = req.erpUser?.defaultCompanyId || req.orgScopes?.[0]?.companyId;
    if (!companyId) {
      throw new BadRequestException(
        'No company scope found. Set a default company or assign an org scope.',
      );
    }
    return companyId;
  }

  private getUserId(req: any): string | undefined {
    return req.erpUser?.id;
  }

  private divisions(req: any): string[] | undefined {
    return divisionFilterFromRequest(req.allowedDivisionIds);
  }

  // ─────────────────────────────────────────────────────── HOST LOOKUP ────
  @Get('hosts')
  @RequirePermission('visitor.entry.create')
  @RequireOrgScope()
  @ApiOperation({ summary: 'Search the employee master for the person being visited' })
  async findHosts(@Query() query: HostLookupQueryDto, @Req() req: any) {
    const data = await this.visitorService.findHosts(this.getCompanyId(req), this.divisions(req), {
      search: query.search,
      divisionId: query.divisionId,
      limit: query.limit,
    });
    return { success: true, data };
  }

  // ──────────────────────────────────────────────────────────── LIST ──────
  @Get('entries')
  @RequirePermission('visitor.entry.view')
  @RequireOrgScope()
  @ApiOperation({ summary: 'List visitor entries (server-side division filtered)' })
  async findAll(@Query() query: ListVisitorEntriesQueryDto, @Req() req: any) {
    const result = await this.visitorService.findAll({
      companyId: this.getCompanyId(req),
      page: query.page,
      limit: query.limit,
      search: query.search,
      status: query.status,
      today: query.today,
      divisionId: query.divisionId,
      locationId: query.locationId,
      allowedDivisionIds: this.divisions(req),
    });
    return { success: true, ...result };
  }

  // ─────────────────────────────────────────────────────────── CREATE ─────
  @Post('entries')
  @RequirePermission('visitor.entry.create')
  @RequireOrgScope()
  @HttpCode(HttpStatus.CREATED)
  @ApiOperation({ summary: 'Register a visitor (server-side Time-In, status PENDING)' })
  @ApiResponse({ status: 201, description: 'Visitor entry created' })
  @ApiResponse({ status: 400, description: 'Invalid division/location/host combination or invalid CNIC' })
  @ApiResponse({ status: 403, description: 'Division outside the caller access scope' })
  async create(@Body() dto: CreateVisitorEntryDto, @Req() req: any) {
    const entry = await this.visitorService.create(
      dto,
      this.getCompanyId(req),
      this.getUserId(req),
      this.divisions(req),
    );
    return { success: true, data: entry, message: 'Visitor registered successfully' };
  }

  // ──────────────────────────────────────────────────────────── EXIT ──────
  @Patch('entries/:id/exit')
  @RequirePermission('visitor.entry.update')
  @RequireOrgScope()
  @ApiOperation({
    summary: 'Record a visitor exit — server-generated Time-Out, status PENDING → COMPLETED',
  })
  @ApiParam({ name: 'id' })
  @ApiResponse({ status: 200, description: 'Visitor checked out; the updated record is returned' })
  @ApiResponse({ status: 400, description: 'Client tried to send a server-owned field (e.g. time_out)' })
  @ApiResponse({ status: 403, description: 'Division outside the caller access scope' })
  @ApiResponse({ status: 404, description: 'Visitor entry not found' })
  @ApiResponse({ status: 409, description: 'Visitor has already checked out (also covers a concurrent/double request)' })
  async checkOut(@Param('id') id: string, @Body() body: ExitVisitorEntryBody, @Req() req: any) {
    this.assertNoClientExitFields(body);
    const entry = await this.visitorService.checkOut(
      id,
      this.getCompanyId(req),
      this.getUserId(req),
      this.divisions(req),
    );
    return { success: true, data: entry, message: 'Visitor exit recorded successfully' };
  }

  /** §4 — the Time-Out is the server's to decide, never the client's. */
  private assertNoClientExitFields(body: unknown): void {
    if (!body || typeof body !== 'object') return;
    const offending = Object.keys(body as Record<string, unknown>).filter((key) =>
      (CLIENT_OWNED_EXIT_KEYS as readonly string[]).includes(key),
    );
    if (offending.length > 0) {
      throw new BadRequestException(
        `Time-Out is generated by the server; these fields are not accepted: ${offending.join(', ')}`,
      );
    }
  }

  // ─────────────────────────────────────────────────────────── DETAIL ─────
  @Get('entries/:id')
  @RequirePermission('visitor.entry.view')
  @RequireOrgScope()
  @ApiOperation({ summary: 'Get one visitor entry (authorised divisions only)' })
  @ApiParam({ name: 'id' })
  async findOne(@Param('id') id: string, @Req() req: any) {
    const entry = await this.visitorService.findOne(id, this.getCompanyId(req), this.divisions(req));
    return { success: true, data: entry };
  }

  // ────────────────────────────────────────────────── HOST CONFIRMATION ──
  @Post('entries/:id/host-confirmation')
  @RequirePermission('visitor.entry.update')
  @RequireOrgScope()
  @ApiOperation({
    summary:
      'Confirm the host (person being visited) actually received the visitor — optional digital signature',
    description:
      'Records host_confirmed / host_confirmed_at / host_confirmed_by. Does NOT set a Time-Out and does NOT change the ' +
      'visitor status: a confirmed host is still PENDING until the exit records the Time-Out. The signature is stored as a ' +
      'private file, never as base64 in the visitor row.',
  })
  @ApiParam({ name: 'id' })
  @ApiResponse({ status: 201, description: 'Host visit confirmed; the updated record is returned' })
  @ApiResponse({ status: 400, description: 'Invalid signature payload, or a client tried to send a server-owned field' })
  @ApiResponse({ status: 403, description: 'Division outside the caller access scope' })
  @ApiResponse({ status: 404, description: 'Visitor entry not found' })
  @ApiResponse({ status: 409, description: 'Host visit has already been confirmed (also covers a concurrent request)' })
  async confirmHostVisit(
    @Param('id') id: string,
    @Body() body: ConfirmHostVisitDto,
    @Req() req: any,
  ) {
    this.assertNoClientHostConfirmationFields(body);
    const entry = await this.visitorService.confirmHostVisit(
      id,
      this.getCompanyId(req),
      this.getUserId(req),
      this.divisions(req),
      body,
    );
    return { success: true, data: entry, message: 'Host visit confirmed successfully' };
  }

  /**
   * §28 — the confirmation flow owns three fields and no more.
   *
   * Same mechanism as the exit endpoint: because the confirmation is a state
   * transition, the client must not be able to state the outcome. Anything that
   * would move the visitor out of PENDING, invent a Time-Out, or forge the audit
   * columns is refused with a 400 before the service is reached.
   */
  private assertNoClientHostConfirmationFields(body: unknown): void {
    if (!body || typeof body !== 'object') return;
    const offending = Object.keys(body as Record<string, unknown>).filter((key) =>
      (CLIENT_OWNED_HOST_KEYS as readonly string[]).includes(key),
    );
    if (offending.length > 0) {
      throw new BadRequestException(
        `Host confirmation is recorded by the server; these fields are not accepted: ${offending.join(', ')}`,
      );
    }
  }

  // ────────────────────────────────────────────────────────── SLIP (#19) ───
  @Get('entries/:id/slip')
  @RequirePermission('visitor.slip.print')
  @RequireOrgScope()
  @ApiOperation({
    summary: 'Authorised print payload for the visitor slip (also used for re-print)',
    description:
      'Returns only what the printed slip needs. Internal STORAGE_PATH values are never exposed — the photo and the ' +
      'signature are fetched through their own authorised endpoints — and the CNIC is returned in the project’s masked ' +
      'privacy form.',
  })
  @ApiParam({ name: 'id' })
  @ApiResponse({ status: 200, description: 'Slip data for the authorised visitor' })
  @ApiResponse({ status: 403, description: 'Division outside the caller access scope' })
  @ApiResponse({ status: 404, description: 'Visitor entry not found' })
  async getSlip(@Param('id') id: string, @Req() req: any) {
    const slip = await this.visitorService.getSlip(id, this.getCompanyId(req), this.divisions(req));
    return { success: true, data: slip };
  }

  @Get('entries/:id/signature')
  @RequirePermission('visitor.entry.view')
  @RequireOrgScope()
  @ApiOperation({ summary: 'Stream the host signature image (permission + division checked)' })
  @ApiParam({ name: 'id' })
  async getSignature(@Param('id') id: string, @Req() req: any, @Res() res: Response) {
    const signature = await this.visitorService.resolveSignature(
      id,
      this.getCompanyId(req),
      this.divisions(req),
    );
    if (!signature) {
      throw new NotFoundException('No signature is attached to this visitor entry');
    }

    res.set({
      'Content-Type': signature.mime,
      'Cache-Control': 'private, no-store',
      'X-Content-Type-Options': 'nosniff',
      'Content-Disposition': 'inline',
    });
    createReadStream(signature.absolutePath).pipe(res);
  }

  // ──────────────────────────────────────────────────────────── PHOTO ─────
  @Post('entries/:id/photo')
  @RequirePermission('visitor.entry.create')
  @RequireOrgScope()
  @UseInterceptors(FileInterceptor('file', { limits: { fileSize: MAX_PHOTO_BYTES } }))
  @ApiOperation({ summary: 'Upload the visitor photo taken with the camera (or uploaded)' })
  @ApiParam({ name: 'id' })
  async uploadPhoto(@Param('id') id: string, @UploadedFile() file: any, @Req() req: any) {
    const entry = await this.visitorService.savePhoto(
      id,
      this.getCompanyId(req),
      this.getUserId(req),
      file,
      this.divisions(req),
    );
    return { success: true, data: entry, message: 'Visitor photo saved' };
  }

  @Get('entries/:id/photo')
  @RequirePermission('visitor.entry.view')
  @RequireOrgScope()
  @ApiOperation({ summary: 'Stream the visitor photo (permission + division checked)' })
  @ApiParam({ name: 'id' })
  async getPhoto(@Param('id') id: string, @Req() req: any, @Res() res: Response) {
    const photo = await this.visitorService.resolvePhoto(
      id,
      this.getCompanyId(req),
      this.divisions(req),
    );
    if (!photo) {
      throw new NotFoundException('No photo is attached to this visitor entry');
    }

    res.set({
      'Content-Type': photo.mime,
      'Cache-Control': 'private, no-store',
      'X-Content-Type-Options': 'nosniff',
      'Content-Disposition': 'inline',
    });
    createReadStream(photo.absolutePath).pipe(res);
  }
}
