import React, { useCallback, useEffect, useState } from 'react';
import { Alert, App as AntApp, Button, Card, Descriptions, Empty, Form, Input, Modal, Select, Space, Table, Tabs, Tag, Typography, Upload } from 'antd';
import { ArrowLeftOutlined, UploadOutlined, PaperClipOutlined } from '@ant-design/icons';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import apiService from '../../services/api';
import { LoadingState, StatusBadge } from '../../components/shared';
import { usePermission } from '../../hooks/usePermission';
import { JOB_CARD_BASE,
  JobCard, OrgOption,
  UUID_RE, uuidRowsOf, errorText, label, ACTION_MAP,
} from './jobCards.types';
import { PageHeader } from '../../components/shared';
import { BuildOutlined } from '@ant-design/icons';
import { MachineProfilePanel } from './MachineProfilePanel';
import { SparePartsPanel } from './SparePartsPanel';

export const JobCardDetail: React.FC = () => {
  const { id } = useParams(); const [searchParams] = useSearchParams(); const navigate = useNavigate(); const { message } = AntApp.useApp(); const { can } = usePermission();
  const [card, setCard] = useState<JobCard | null>(null); const [related, setRelated] = useState<Record<string, any[]>>({}); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [assignOpen, setAssignOpen] = useState(false); const [editOpen, setEditOpen] = useState(false); const [categories, setCategories] = useState<OrgOption[]>([]); const [departments, setDepartments] = useState<OrgOption[]>([]); const [assignForm] = Form.useForm(); const [editForm] = Form.useForm();
  const load = useCallback(async () => { if (!id) return; setLoading(true); setError(''); try { const [job, parts, logs, attachments, history, technicians] = await Promise.all([apiService.get<JobCard>(`${JOB_CARD_BASE}/${id}`), apiService.get<any[]>(`${JOB_CARD_BASE}/${id}/parts`), apiService.get<any[]>(`${JOB_CARD_BASE}/${id}/work-logs`), apiService.get<any[]>(`${JOB_CARD_BASE}/${id}/attachments`), apiService.get<any[]>(`${JOB_CARD_BASE}/${id}/history`), apiService.get<any[]>(`${JOB_CARD_BASE}/${id}/technicians`)]); setCard(job); setRelated({ parts, logs, attachments, history, technicians }); } catch (e) { setError(errorText(e)); } finally { setLoading(false); } }, [id]);
  useEffect(() => { load(); }, [load]);
  useEffect(() => { if (card && searchParams.get('edit') === '1') setEditOpen(true); }, [card, searchParams]);
  useEffect(() => { if (!card) return; editForm.setFieldsValue({ complaint: card.complaint, complaintCategoryId: card.complaintCategoryId || undefined, assignedDepartmentId: card.assignedDepartmentId || undefined, description: card.description || undefined }); const companyId = card.companyId; const divisionId = card.machine?.divisionId; const sectionId = card.machine?.sectionId; if (companyId) apiService.get<any>('/master-data/maintenance/categories/complaint', { companyId }).then(r => setCategories(uuidRowsOf(r))).catch(() => setCategories([])); if (companyId && divisionId && sectionId) apiService.get<any>('/departments', { companyId, divisionId, sectionId, limit: 100 }).then(r => setDepartments(uuidRowsOf(r))).catch(() => setDepartments([])); }, [card, editForm]);
  const run = async (action: { label: string; endpoint: string; permission: string }, body: any = {}) => { if (!id) return; setBusy(true); try { await apiService.post(`${JOB_CARD_BASE}/${id}/${action.endpoint}`, body); message.success(`${action.label} completed`); await load(); } catch (e) { message.error(errorText(e)); } finally { setBusy(false); } };
  const trigger = (action: { label: string; endpoint: string; permission: string }) => {
    if (action.endpoint === 'assign') { assignForm.resetFields(); setAssignOpen(true); return; }
    Modal.confirm({ title: `${action.label} this job card?`, onOk: () => run(action, action.endpoint === 'reject' ? { reason: 'Rejected during review' } : {}) });
  };
  const saveEdit = async (values: JobCard) => { if (!id) return; setBusy(true); try { await apiService.patch(`${JOB_CARD_BASE}/${id}`, { complaint: values.complaint, complaintCategoryId: values.complaintCategoryId || undefined, assignedDepartmentId: values.assignedDepartmentId || undefined, description: values.description || undefined }); message.success('Job card updated'); setEditOpen(false); await load(); } catch (e) { message.error(errorText(e)); } finally { setBusy(false); } };
  if (loading) return <LoadingState />; if (error) return <Alert type="error" message="Unable to load job card" description={error} action={<Button onClick={load}>Retry</Button>} />; if (!card) return <Empty description="Job card not found" />;
  const actions = (ACTION_MAP[card.currentStatus] || []).filter(a => can(a.permission));
  const machineHistory = related.history || [];
  return <div><PageHeader icon={<BuildOutlined />} title={card.jobCardNo || 'Maintenance Job Card'} subtitle="Maintenance work order" gradient="linear-gradient(135deg, #1f6f78 0%, #2e8b8b 100%)" showBreadcrumbs /><Space style={{ marginBottom: 16 }}><Button icon={<ArrowLeftOutlined />} onClick={() => navigate('/maintenance/job-cards')}>Back</Button>{can('maintenance.job_card.update') && card.currentStatus !== 'APPROVED' && <Button onClick={() => setEditOpen(true)}>Edit</Button>}{actions.map(a => <Button key={a.endpoint} type="primary" loading={busy} onClick={() => trigger(a)}>{a.label}</Button>)}</Space>
    <Card title="Organization & Asset" style={{ marginBottom: 16 }}><Descriptions column={{ xs: 1, sm: 2, lg: 3 }}><Descriptions.Item label="Company">{card.company?.name || 'Company unavailable'}</Descriptions.Item><Descriptions.Item label="Division">{card.division?.name || card.machine?.division?.name || 'Division unavailable'}</Descriptions.Item><Descriptions.Item label="Section">{card.section?.name || card.machine?.section?.name || 'Section unavailable'}</Descriptions.Item><Descriptions.Item label="Department">{card.machine?.department?.name || card.assignedDepartment?.name || 'Department unavailable'}</Descriptions.Item><Descriptions.Item label="Machine">{card.machine ? `${card.machine.machineCode || card.machine.machineNumber || ''} ${card.machine.name || ''}`.trim() || 'Machine unavailable' : 'Machine unavailable'}</Descriptions.Item><Descriptions.Item label="Status"><StatusBadge status={card.currentStatus} /></Descriptions.Item><Descriptions.Item label="Priority"><StatusBadge status={card.priority} /></Descriptions.Item><Descriptions.Item label="Type"><Tag color={card.maintenanceType === 'BREAKDOWN' ? 'red' : card.maintenanceType === 'PREVENTIVE' ? 'green' : card.maintenanceType === 'EMERGENCY' ? 'volcano' : 'blue'}>{label(card.maintenanceType)}</Tag></Descriptions.Item><Descriptions.Item label="Requested">{card.requestedAt ? new Date(card.requestedAt).toLocaleString() : '—'}</Descriptions.Item></Descriptions></Card>
    {card.machineId && <MachineProfilePanel machineId={card.machineId} compact />}
    <Card title="Complaint & Request" style={{ marginBottom: 16 }}><Descriptions column={{ xs: 1, md: 2 }}><Descriptions.Item label="Complaint">{card.complaint}</Descriptions.Item><Descriptions.Item label="Category">{card.complaintCategory?.name || '—'}</Descriptions.Item><Descriptions.Item label="Description">{card.description || '—'}</Descriptions.Item><Descriptions.Item label="Reported by">{card.requestedByUser?.displayName || card.requestedByUser?.email || '—'}</Descriptions.Item>{card.diagnosis && <Descriptions.Item label="Diagnosis">{card.diagnosis}</Descriptions.Item>}{card.correctiveAction && <Descriptions.Item label="Corrective Action">{card.correctiveAction}</Descriptions.Item>}{card.preventiveAction && <Descriptions.Item label="Preventive Action">{card.preventiveAction}</Descriptions.Item>}</Descriptions></Card>
    <Card style={{ marginTop: 16 }}><Tabs items={[{ key: 'history', label: 'Status History', children: <Table rowKey="id" pagination={false} dataSource={machineHistory} columns={[{ title: 'From', dataIndex: 'fromStatus', render: label }, { title: 'To', dataIndex: 'toStatus', render: label }, { title: 'Remarks', dataIndex: 'remarks' }, { title: 'Changed', dataIndex: 'changedAt', render: (v: string) => v && new Date(v).toLocaleString() }]} /> }, { key: 'parts', label: 'Parts', children: <SparePartsPanel jobCardId={card.id} companyId={card.companyId} isEditable={card.currentStatus !== 'APPROVED'} onUpdate={load} /> }, { key: 'logs', label: 'Work Logs', children: <Table rowKey="id" pagination={false} dataSource={related.logs} columns={[{ title: 'Work', dataIndex: 'workDescription' }, { title: 'Remarks', dataIndex: 'remarks' }, { title: 'Created', dataIndex: 'createdAt', render: (v: string) => v && new Date(v).toLocaleString() }]} /> }, { key: 'attachments', label: 'Attachments', children: related.attachments?.length ? <Table rowKey="id" pagination={false} dataSource={related.attachments} columns={[{ title: 'File', dataIndex: 'fileName' }, { title: 'Description', dataIndex: 'description' }]} /> : <Empty description="No attachments" /> }, { key: 'technicians', label: 'Technicians', children: <Table rowKey="id" pagination={false} dataSource={related.technicians} columns={[{ title: 'Technician', render: (_: any, r: JobCard) => r.technicianUser?.displayName || r.technicianUser?.email || r.technicianUserId }, { title: 'Role', dataIndex: 'role' }]} /> }]} /></Card>
    <Modal title="Edit job card" open={editOpen} confirmLoading={busy} onCancel={() => setEditOpen(false)} onOk={() => editForm.submit()}><Form form={editForm} layout="vertical" onFinish={saveEdit}><Form.Item name="complaint" label="Complaint" rules={[{ required: true }]}><Input.TextArea rows={3} /></Form.Item><Form.Item name="complaintCategoryId" label="Complaint category"><Select allowClear options={categories.map(category => ({ value: category.id, label: category.name || category.code || category.id }))} /></Form.Item><Form.Item name="assignedDepartmentId" label="Department"><Select allowClear options={departments.map(department => ({ value: department.id, label: department.name || department.code || department.id }))} /></Form.Item><Form.Item name="description" label="Description"><Input.TextArea rows={3} /></Form.Item></Form></Modal><Modal title="Assign technicians" open={assignOpen} confirmLoading={busy} onCancel={() => setAssignOpen(false)} onOk={() => assignForm.submit()}><Form form={assignForm} layout="vertical" onFinish={async values => { await run({ label: 'Assignment', endpoint: 'assign', permission: 'maintenance.job_card.assign' }, { technicianUserIds: values.technicianUserIds.split(',').map((v: string) => v.trim()).filter(Boolean), teamCode: values.teamCode, remarks: values.remarks }); setAssignOpen(false); }}><Form.Item name="technicianUserIds" label="Technician user IDs (comma separated)" rules={[{ required: true }]}><Input placeholder="UUID, UUID" /></Form.Item><Form.Item name="teamCode" label="Team code"><Input /></Form.Item><Form.Item name="remarks" label="Remarks"><Input.TextArea rows={2} /></Form.Item></Form></Modal>
  </div>;
};

export default JobCardDetail;
