-- Migration: Store Remediation (TASK 10)
-- 1. Registers the legitimate system/service actor used by the automatic
--    replenishment processor so created_by / updated_by are real, resolvable
--    erp_users ids (never '', never a random uuid, never a hardcoded user uuid).
-- 2. Grants INVENTORY two read-only procurement VIEW permissions required by the
--    store receipts page dropdowns (supplier + PO lookups). The store receipts
--    page itself is served by a store-facing controller gated with store.receive.*
--    so no broad procurement grants are added.

-- =====================================================
-- 1. SYSTEM SERVICE ACTOR FOR AUTOMATIC REPLENISHMENT
-- =====================================================
-- The id and auth_user_id are generated by the database (never hardcoded).
-- The backend resolves this account at runtime by username.
INSERT INTO public.erp_users (auth_user_id, email, username, display_name, status, is_active)
SELECT gen_random_uuid(), 'system.replenishment@erp.local', 'system.replenishment', 'System (Automatic Replenishment)', 'ACTIVE', true
WHERE NOT EXISTS (
    SELECT 1 FROM public.erp_users WHERE username = 'system.replenishment' OR email = 'system.replenishment@erp.local'
);

-- =====================================================
-- 2. STORE RECEIPTS PAGE - REFERENCE READ GRANTS
-- =====================================================
-- The store material-receipts page performs supplier + purchase-order lookups
-- before creating a GRN. Grant INVENTORY ONLY these two read-only VIEW
-- permissions; all receipt operations remain behind store.receive.*.
INSERT INTO role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM roles r
CROSS JOIN permissions p
WHERE r.role_code = 'INVENTORY'
  AND p.permission_code IN ('procurement.supplier.view', 'procurement.order.view')
ON CONFLICT (role_id, permission_id) DO NOTHING;