-- ERP-00071: Visitor Slip + Print + Host Confirmation (Prompt #19 — Phase 3)
-- Migration: 20260930000000_erp_00071_visitor_slip.sql
--
-- SCOPE
--   Prompt #19 adds the physical document and the host confirmation to the
--   Prompt #17 register + Prompt #18 exit:
--     Visitor Slip → printable/re-printable → Host Confirmation → (later) Time-Out
--
--   STRICTLY ADDITIVE. Nothing is renamed, dropped or retyped, and the Prompt
--   #17 / #18 columns (time_in, time_out, status, exited_by, photo_path, …) are
--   REUSED, never duplicated:
--
--   1. `visitor_reference` — the human-readable reception reference printed on
--      the slip. Generated by the SERVER on create, in the same shape the
--      project already uses for package numbers (`PKG-2026000001`), so security
--      and reception can quote a short business reference instead of a UUID
--      (§5). UNIQUE — it is a reference, not a label.
--   2. `host_confirmed` / `host_confirmed_at` / `host_confirmed_by` — the host
--      (person being visited) confirming the visitor actually reached them
--      (§12/§15/§18). NOT a status change: confirmation never sets a Time-Out
--      and never moves PENDING → COMPLETED (§28).
--   3. `signature_path` / `signature_mime` / `signature_captured_at` /
--      `signature_captured_by` — the optional digital signature, stored as a
--      private storage reference exactly like `photo_path` (never a base64 blob
--      in the row, never a public URL) (§14/§18/§22).
--   4. One permission, `visitor.slip.print`, in the existing
--      <module>.<resource>.<action> convention (`visitor.entry.view`,
--      `visitor.entry.update`, `location.update`, …). Printing a slip is a
--      distinct capability from viewing a row, so it gets its own code; host
--      confirmation reuses `visitor.entry.update` because that is literally
--      what it is — an update of the visitor entry (§19).
--
--   The physical signature area required by §13 lives on the PRINTED slip
--   (frontend/src/utils/printTemplates.ts → printVisitorSlipDocument) and
--   therefore needs no column here.
--
-- NOT IN THIS MIGRATION
--   No dashboard / current-day monitoring tables (#20), no vehicle tables, no
--   SMS/WhatsApp fields. Prompts #20/#21 must not be pre-built.
--
-- ROLLBACK (see the comment at the end of this file).

-- =====================================================
-- 1. VISITOR REFERENCE (human-readable, §5)
-- =====================================================
--   Format: VIS-<server year>-<6 digits>, e.g. VIS-2026-000001.
--   Column added as NULL first so the table locks for a moment rather than
--   blocking writes, then backfilled deterministically from each row's own
--   created_at (year + creation order), and only then made NOT NULL.
ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS visitor_reference VARCHAR(30) NULL;

COMMENT ON COLUMN public.visitor_entries.visitor_reference IS
    'Human-readable visitor/reception reference printed on the slip (Prompt #19). Server-generated on create, format VIS-<year>-<6 digits>.';

-- Backfill in creation order so a re-run is deterministic and the printed
-- references stay in the same order the visitors actually arrived.
-- (A window function is not allowed directly in UPDATE, hence the sub-select.)
UPDATE public.visitor_entries ve
   SET visitor_reference = seq.visitor_reference
  FROM (
        SELECT id,
               'VIS-'
                 || to_char(created_at AT TIME ZONE 'UTC', 'YYYY')
                 || '-' || lpad(
                      (row_number() OVER (
                          PARTITION BY to_char(created_at AT TIME ZONE 'UTC', 'YYYY')
                          ORDER BY created_at, id
                      ))::text, 6, '0') AS visitor_reference
          FROM public.visitor_entries
         WHERE visitor_reference IS NULL
       ) seq
 WHERE ve.id = seq.id;

ALTER TABLE public.visitor_entries
    ALTER COLUMN visitor_reference SET NOT NULL;

-- Reception may look a visitor up by the printed reference, and two visitors
-- must never share one. The index serves both.
CREATE UNIQUE INDEX IF NOT EXISTS uq_visitor_entries_reference
    ON public.visitor_entries(visitor_reference);

-- =====================================================
-- 2. HOST CONFIRMATION (§12/§15/§18/§28)
-- =====================================================
ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS host_confirmed BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS host_confirmed_at TIMESTAMPTZ NULL;

-- Plain uuid, no FK — exactly like created_by / updated_by / exited_by.
ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS host_confirmed_by UUID NULL;

COMMENT ON COLUMN public.visitor_entries.host_confirmed IS
    'True once the host (person being visited) confirmed the visitor reached them. Independent of the exit: a visitor can be host-confirmed and still PENDING (§15/§28).';
COMMENT ON COLUMN public.visitor_entries.host_confirmed_at IS
    'Server timestamp of the host confirmation.';
COMMENT ON COLUMN public.visitor_entries.host_confirmed_by IS
    'Authenticated ERP user who recorded the host confirmation. The person being visited stays in host_employee_id / host_name_snapshot — the system does NOT verify that the signed-in user is the host (§17).';

-- =====================================================
-- 3. OPTIONAL DIGITAL SIGNATURE (§14/§18/§22)
-- =====================================================
--   A storage reference, never image data in the row: the file lives under
--   STORAGE_PATH and is served only through the authorised GET endpoint, with
--   the same private/no-store headers as the visitor photo.
ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS signature_path VARCHAR(500) NULL;

ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS signature_mime VARCHAR(100) NULL;

ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS signature_captured_at TIMESTAMPTZ NULL;

ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS signature_captured_by UUID NULL;

COMMENT ON COLUMN public.visitor_entries.signature_path IS
    'Path inside STORAGE_PATH of the host signature image, or NULL. Never exposed to the client; served only by the authorised signature endpoint.';

-- =====================================================
-- 4. PERMISSION  (existing <module>.<resource>.<action> convention)
-- =====================================================
--   Purely additive: WHERE NOT EXISTS + ON CONFLICT DO NOTHING, so no existing
--   user, role or permission is changed or removed.
INSERT INTO permissions (permission_code, name, module, resource, action, description, status)
SELECT * FROM (VALUES
  ('visitor.slip.print','Print Visitor Slip','visitor','slip','PRINT','Print or re-print the visitor slip and its host confirmation / signature area','ACTIVE')
) AS v(permission_code, name, module, resource, action, description, status)
WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.permission_code = v.permission_code);

-- SUPER_ADMIN / ADMIN / MANAGEMENT work the gate and produce the slips.
--   (ADMIN still gets everything except DELETE, per the project backfill convention.)
INSERT INTO role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM roles r CROSS JOIN permissions p
WHERE r.role_code IN ('SUPER_ADMIN', 'ADMIN', 'MANAGEMENT')
  AND p.permission_code = 'visitor.slip.print'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- REPORT_VIEWER stays read-only.

-- =====================================================
-- VERIFY (read-only)
--   SELECT column_name, data_type, is_nullable
--     FROM information_schema.columns
--    WHERE table_name = 'visitor_entries'
--      AND column_name IN ('visitor_reference','host_confirmed','host_confirmed_at',
--                          'host_confirmed_by','signature_path','signature_mime',
--                          'signature_captured_at','signature_captured_by')
--    ORDER BY column_name;
--   SELECT indexname, indexdef FROM pg_indexes
--    WHERE indexname = 'uq_visitor_entries_reference';
--   SELECT visitor_reference, status, host_confirmed, time_out FROM visitor_entries;
--   SELECT p.permission_code, r.role_code FROM role_permissions rp
--     JOIN roles r ON r.id = rp.role_id
--     JOIN permissions p ON p.id = rp.permission_id
--    WHERE p.permission_code LIKE 'visitor.%' ORDER BY p.permission_code, r.role_code;
--
-- ROLLBACK
--   DELETE FROM role_permissions WHERE permission_id IN
--     (SELECT id FROM permissions WHERE permission_code = 'visitor.slip.print');
--   DELETE FROM permissions WHERE permission_code = 'visitor.slip.print';
--   DROP INDEX IF EXISTS public.uq_visitor_entries_reference;
--   ALTER TABLE public.visitor_entries
--     DROP COLUMN IF EXISTS signature_captured_by,
--     DROP COLUMN IF EXISTS signature_captured_at,
--     DROP COLUMN IF EXISTS signature_mime,
--     DROP COLUMN IF EXISTS signature_path,
--     DROP COLUMN IF EXISTS host_confirmed_by,
--     DROP COLUMN IF EXISTS host_confirmed_at,
--     DROP COLUMN IF EXISTS host_confirmed,
--     DROP COLUMN IF EXISTS visitor_reference;
-- =====================================================
