-- ERP-00070: Visitor Exit / Time-Out (Prompt #18 — Phase 2)
-- Migration: 20260929000000_erp_00070_visitor_exit.sql
--
-- SCOPE
--   Prompt #18 turns the Prompt #17 gate register into a full visit lifecycle:
--     Visitor Entry → PENDING → (exit) → COMPLETED
--
--   STRICTLY ADDITIVE. Nothing is renamed, dropped, retyped or re-seeded:
--     1. `visitor_entries.exited_by` — who recorded the Time-Out (§17).
--        `time_out` and `status` already exist from ERP-00069 and are REUSED
--        (`status` already CHECKs 'COMPLETED'); no duplicate columns.
--     2. One partial index for the "who is still inside" query (§13/§19).
--     3. One permission, `visitor.entry.update`, in the existing
--        <module>.<resource>.<action> convention used by Prompt #17
--        (`visitor.entry.view` / `visitor.entry.create`, `location.update`, …)
--        so Time-Out is not folded into `visitor.entry.create` (§21).
--
--   The Time-Out value itself is ALWAYS generated by the server
--   (VisitorEntryService.checkOut) — the API never accepts it from a client.
--
-- NOT IN THIS MIGRATION
--   No visitor slip / print / signature columns (#19), no dashboard or
--   current-day statistics tables (#20), no vehicle tables.
--
-- ROLLBACK (see the comment at the end of this file).

-- =====================================================
-- 1. EXIT AUDIT COLUMN
-- =====================================================
--   Same shape as created_by / updated_by (plain uuid, no FK — those columns
--   are not FK-constrained either), so a later photo upload that bumps
--   updated_by can never hide who actually recorded the Time-Out.
ALTER TABLE public.visitor_entries
    ADD COLUMN IF NOT EXISTS exited_by UUID NULL;

COMMENT ON COLUMN public.visitor_entries.exited_by IS
    'User who recorded the visitor Time-Out (Prompt #18). NULL while the visit is still PENDING.';

-- =====================================================
-- 2. PENDING ("still inside") INDEX
-- =====================================================
--   Justified by the actual query the list issues for the Pending filter and the
--   current-day view: company + division scope, status = 'PENDING',
--   time_out IS NULL, ordered by time_in DESC. Rows leave this index the
--   moment they are checked out, so it stays small no matter how much visit
--   history accumulates. The existing idx_visitor_entries_status /
--   idx_visitor_entries_division_time_in keep the unfiltered list fast.
CREATE INDEX IF NOT EXISTS idx_visitor_entries_pending
    ON public.visitor_entries(division_id, time_in DESC)
    WHERE status = 'PENDING' AND time_out IS NULL;

-- =====================================================
-- 3. PERMISSION  (existing <module>.<resource>.<action> convention)
-- =====================================================
--   Purely additive: WHERE NOT EXISTS + ON CONFLICT DO NOTHING, so no existing
--   user, role or permission is changed or removed.
INSERT INTO permissions (permission_code, name, module, resource, action, description, status)
SELECT * FROM (VALUES
  ('visitor.entry.update','Update Visitor Entry (Time-Out)','visitor','entry','UPDATE','Record a visitor exit: server-generated Time-Out, status COMPLETED','ACTIVE')
) AS v(permission_code, name, module, resource, action, description, status)
WHERE NOT EXISTS (SELECT 1 FROM permissions p WHERE p.permission_code = v.permission_code);

-- SUPER_ADMIN / ADMIN / MANAGEMENT operate the gate, so they can check visitors out.
--   (ADMIN still gets everything except DELETE, per the project backfill convention.)
INSERT INTO role_permissions (role_id, permission_id, status)
SELECT r.id, p.id, 'ACTIVE'
FROM roles r CROSS JOIN permissions p
WHERE r.role_code IN ('SUPER_ADMIN', 'ADMIN', 'MANAGEMENT')
  AND p.permission_code = 'visitor.entry.update'
ON CONFLICT (role_id, permission_id) DO NOTHING;

-- REPORT_VIEWER stays read-only — no UPDATE permission is granted to it.

-- =====================================================
-- VERIFY (read-only)
--   SELECT column_name, data_type FROM information_schema.columns
--     WHERE table_name = 'visitor_entries' AND column_name = 'exited_by';
--   SELECT indexname FROM pg_indexes WHERE tablename = 'visitor_entries'
--     AND indexname = 'idx_visitor_entries_pending';
--   SELECT permission_code FROM permissions
--     WHERE permission_code LIKE 'visitor.entry.%';
--   SELECT r.role_code FROM role_permissions rp
--     JOIN roles r ON r.id = rp.role_id
--     JOIN permissions p ON p.id = rp.permission_id
--    WHERE p.permission_code = 'visitor.entry.update' ORDER BY r.role_code;
--     -- expect SUPER_ADMIN, ADMIN, MANAGEMENT (never REPORT_VIEWER)
--
-- ROLLBACK
--   DROP INDEX IF EXISTS public.idx_visitor_entries_pending;
--   ALTER TABLE public.visitor_entries DROP COLUMN IF EXISTS exited_by;
--   DELETE FROM role_permissions WHERE permission_id IN
--     (SELECT id FROM permissions WHERE permission_code = 'visitor.entry.update');
--   DELETE FROM permissions WHERE permission_code = 'visitor.entry.update';
-- =====================================================
