import { Entity, Column, ManyToOne, JoinColumn } from 'typeorm';
import { BaseEntity } from '../../../common/base.entity';
import { Company } from '../../organization/entities/company.entity';
import { Division } from '../../organization/entities/division.entity';
import { HrEmployee } from '../../hr/entities/hr-employee.entity';
import { Location } from './location.entity';

export enum VisitorEntryStatus {
  /** Registered at the gate, Time-In recorded, not yet departed. */
  PENDING = 'PENDING',
  /** Visitor confirmed on site. No writer in Prompt #18 — reserved for later phases. */
  INSIDE = 'INSIDE',
  /** Time-Out recorded — the visit is closed and kept as history (§18). */
  COMPLETED = 'COMPLETED',
  /** Registered then cancelled at the gate — never check-out eligible. */
  CANCELLED = 'CANCELLED',
}

/**
 * Visitor register — `visitor_entries` (migrations ERP-00069, ERP-00070, ERP-00071).
 *
 * One row = one visit (§18). There is no separate history table.
 *   - `timeIn`  is written SERVER-SIDE only (never accepted from the client).
 *   - `timeOut` is written SERVER-SIDE only, exactly once, by the Prompt #18
 *     exit endpoint; `exitedBy` records who did it.
 *   - `status` moves PENDING → COMPLETED on exit and is never reset afterwards.
 *   - `hostEmployeeId` points at the existing employee master, and
 *     `hostNameSnapshot` keeps the record readable after that employee is
 *     renamed or archived.
 *   - `photoPath` is a path inside STORAGE_PATH, deliberately NOT a public URL:
 *     the photo is served only through the authorised GET .../photo endpoint.
 *   - `visitorReference` is the server-generated reception reference printed on
 *     the slip, and `hostConfirmed*` / `signature*` are the Prompt #19 host
 *     confirmation. Neither of those ever touches `status`, `timeIn` or
 *     `timeOut` — a confirmed host is still a PENDING visitor until Time-Out.
 */
@Entity('visitor_entries')
export class VisitorEntry extends BaseEntity {
  /**
   * Human-readable reception reference printed on the visitor slip
   * (Prompt #19 §5, migration ERP-00071).
   *
   * Generated by the SERVER on create, in the shape the project already uses
   * for package numbers (`PKG-2026000001`): `VIS-<year>-<6 digits>`. It is a
   * business reference, never the visual identifier of the UUID, and reception /
   * security can quote it on the phone. UNIQUE in the database.
   */
  @Column({ name: 'visitor_reference', type: 'varchar', length: 30 })
  visitorReference: string;

  @Column({ name: 'company_id', type: 'uuid' })
  companyId: string;

  @ManyToOne(() => Company)
  @JoinColumn({ name: 'company_id' })
  company: Company;

  @Column({ name: 'division_id', type: 'uuid' })
  divisionId: string;

  @ManyToOne(() => Division, { nullable: true })
  @JoinColumn({ name: 'division_id' })
  division: Division;

  @Column({ name: 'location_id', type: 'uuid' })
  locationId: string;

  @ManyToOne(() => Location, { nullable: true })
  @JoinColumn({ name: 'location_id' })
  location: Location;

  @Column({ name: 'visitor_name', type: 'varchar', length: 255 })
  visitorName: string;

  @Column({ type: 'varchar', length: 20, nullable: true })
  cnic: string | null;

  @Column({ type: 'varchar', length: 20, nullable: true })
  mobile: string | null;

  @Column({ name: 'visitor_company', type: 'varchar', length: 255, nullable: true })
  visitorCompany: string | null;

  /** Person being visited — reference to the existing employee master. */
  @Column({ name: 'host_employee_id', type: 'uuid', nullable: true })
  hostEmployeeId: string | null;

  @ManyToOne(() => HrEmployee, { nullable: true })
  @JoinColumn({ name: 'host_employee_id' })
  hostEmployee: HrEmployee | null;

  /** Copy of the host's name at registration time (historical accuracy). */
  @Column({ name: 'host_name_snapshot', type: 'varchar', length: 255, nullable: true })
  hostNameSnapshot: string | null;

  @Column({ name: 'photo_path', type: 'varchar', length: 500, nullable: true })
  photoPath: string | null;

  @Column({ name: 'photo_mime', type: 'varchar', length: 100, nullable: true })
  photoMime: string | null;

  /** Server-generated. Never read from the request payload. */
  @Column({ name: 'time_in', type: 'timestamp with time zone' })
  timeIn: Date;

  /**
   * Server-generated Time-Out (Prompt #18). NULL while the visitor is still on
   * site; written once by `VisitorEntryService.checkOut` and never overwritten.
   */
  @Column({ name: 'time_out', type: 'timestamp with time zone', nullable: true })
  timeOut: Date | null;

  /**
   * Who recorded the Time-Out (migration ERP-00070, §17).
   *
   * `updated_by`/`updated_at` alone are not enough: a later photo upload bumps
   * them, which would erase the record of who checked the visitor out. Same
   * shape as `created_by` (plain uuid, no FK).
   */
  @Column({ name: 'exited_by', type: 'uuid', nullable: true })
  exitedBy: string | null;

  @Column({ type: 'varchar', length: 20, default: VisitorEntryStatus.PENDING })
  status: VisitorEntryStatus;

  // ─────────────────────── Prompt #19 — host confirmation & signature ──────
  /**
   * True once the host (the person being visited) confirmed the visitor
   * actually reached them (Prompt #19 §12/§15).
   *
   * INDEPENDENT of the visit status by design: a host-confirmed visitor is
   * still PENDING until the exit records a Time-Out, and a COMPLETED visitor
   * may never have been confirmed. It never sets `timeOut` and never moves
   * PENDING → COMPLETED (§28).
   */
  @Column({ name: 'host_confirmed', type: 'boolean', default: false })
  hostConfirmed: boolean;

  /** Server timestamp of the host confirmation. */
  @Column({ name: 'host_confirmed_at', type: 'timestamp with time zone', nullable: true })
  hostConfirmedAt: Date | null;

  /**
   * Authenticated ERP user who recorded the host confirmation — NOT a claim
   * that this user is the host (§17). The person being visited stays in
   * `hostEmployeeId` / `hostNameSnapshot`, and the system never asserts an
   * identity it cannot verify. Plain uuid, no FK, like `created_by`.
   */
  @Column({ name: 'host_confirmed_by', type: 'uuid', nullable: true })
  hostConfirmedBy: string | null;

  /**
   * Optional digital signature of the host (Prompt #19 §14).
   *
   * A path inside STORAGE_PATH — deliberately NOT image data in the row and
   * NOT a public URL, exactly like `photoPath`. It is served only through the
   * authorised GET .../signature endpoint. The printed slip always carries a
   * physical signature area regardless of this field (§13).
   */
  @Column({ name: 'signature_path', type: 'varchar', length: 500, nullable: true })
  signaturePath: string | null;

  @Column({ name: 'signature_mime', type: 'varchar', length: 100, nullable: true })
  signatureMime: string | null;

  /**
   * When/who captured the signature image. Kept separate from
   * `hostConfirmedAt`/`hostConfirmedBy` so re-capturing a signature (clear →
   * redo) never rewrites the confirmation audit trail (§18).
   */
  @Column({ name: 'signature_captured_at', type: 'timestamp with time zone', nullable: true })
  signatureCapturedAt: Date | null;

  @Column({ name: 'signature_captured_by', type: 'uuid', nullable: true })
  signatureCapturedBy: string | null;
}
